name: Show alf

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2021.3.1f1]
    steps:
    - run: echo -n -e "HELLO\n !\n World!" > text.txt

    - uses: Mathijs-Marks/Astral-Drift@Develop
      with:
        unity-version: ${{ matrix.unity-version }}

    - run: /opt/Unity/Editor/Unity -quit -batchMode -logFile -noGraphics -createManualActivationFile || exit 0
    - run: cat Unity_v${{ matrix.unity-version }}.alf
